services:
  # ============================================
  # TRAEFIK - Reverse Proxy + Load Balancer
  # ============================================
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=honza.doan@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`traefik.izzi.local`)"
        - "traefik.http.routers.api.service=api@internal"

  # ============================================
  # POSTGRES DATABASE
  # ============================================
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: school_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    secrets:
      - db_user
      - db_password
    deploy:
      replicas: 1  # As per requirements
      placement:
        constraints:
          - node.role == manager  # Keep DB on manager for simplicity
      restart_policy:
        condition: on-failure

  # ============================================
  # BACKEND API
  # ============================================
  backend:
    image: ghcr.io/l3miage-diabyfa/projet-annuel-s4-backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/school_db
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      FRONTEND_URL: https://izzi.local
    networks:
      - backend-network
      - traefik-public
    secrets:
      - jwt_secret
      - db_password
    deploy:
      replicas: 2  # As per requirements (minimum 2)
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`api.izzi.local`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certresolver=myresolver"
        - "traefik.http.services.backend.loadbalancer.server.port=3000"

  # ============================================
  # FRONTEND
  # ============================================
  frontend:
    image: ghcr.io/l3miage-diabyfa/projet-annuel-s4-frontend:latest
    environment:
      NEXT_PUBLIC_API_URL: https://api.izzi.local
      NODE_ENV: production
    networks:
      - traefik-public
    deploy:
      replicas: 3  # As per requirements (minimum 3)
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`izzi.local`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=myresolver"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"

# ============================================
# NETWORKS
# ============================================
networks:
  traefik-public:
    driver: overlay
    attachable: true
  backend-network:
    driver: overlay
    internal: true

# ============================================
# VOLUMES
# ============================================
volumes:
  postgres-data:
  traefik-certificates:

# ============================================
# SECRETS
# ============================================
secrets:
  db_user:
    external: true
  db_password:
    external: true
  jwt_secret:
    external: true