services:
  # ============================================
  # TRAEFIK - Reverse Proxy + Load Balancer
  # ============================================
  traefik:
    image: traefik:v2.11
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager

  # ============================================
  # POSTGRES DATABASE
  # ============================================
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: school_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    secrets:
      - db_user
      - db_password
    deploy:
      replicas: 1  # As per requirements
      placement:
        constraints:
          - node.role == manager  # Keep DB on manager for simplicity
      restart_policy:
        condition: on-failure

  # ============================================
  # BACKEND API
  # ============================================
  backend:
    image: ghcr.io/l3miage-diabyfa/projet-annuel-s4-backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/school_db
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      FRONTEND_URL: http://64.227.82.151
      PORT: 3000
      STRIPE_SECRET_KEY: sk_test_51Sld2C0RT2eFQsc53EdWfSDVJ1sDvuSXV34c0coq4kAg6PvAXluJRGOxTHWrbx6KpQFnzaKYv9eE3RcsdKlNZjMI0096KpBSf6
    networks:
      - backend-network
      - traefik-public
    secrets:
      - jwt_secret
      - db_password
    deploy:
      replicas: 2  # As per requirements (minimum 2)
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=(PathPrefix(`/api`) || PathPrefix(`/user`) || PathPrefix(`/classes`) || PathPrefix(`/subscription`) || PathPrefix(`/health`) || PathPrefix(`/contact`) || PathPrefix(`/establishment`) || PathPrefix(`/subjects`) || PathPrefix(`/reviews`))"
        - "traefik.http.routers.backend.entrypoints=web"
        - "traefik.http.routers.backend.priority=10"
        - "traefik.http.services.backend.loadbalancer.server.port=3000"

  # ============================================
  # FRONTEND
  # ============================================
  frontend:
    image: ghcr.io/l3miage-diabyfa/projet-annuel-s4-frontend:latest
    environment:
      NEXT_PUBLIC_API_URL: http://64.227.82.151
      NODE_ENV: production
    networks:
      - traefik-public
    deploy:
      replicas: 3  # As per requirements (minimum 3)
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
        - "traefik.http.routers.frontend.entrypoints=web"
        - "traefik.http.routers.frontend.priority=1"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"

# ============================================
# NETWORKS
# ============================================
networks:
  traefik-public:
    driver: overlay
    attachable: true
  backend-network:
    driver: overlay
    internal: true

# ============================================
# VOLUMES
# ============================================
volumes:
  postgres-data:

# ============================================
# SECRETS
# ============================================
secrets:
  db_user:
    external: true
  db_password:
    external: true
  jwt_secret:
    external: true