import type { Metadata } from "next";
import { Poppins, Mochiy_Pop_One, Pacifico } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { UserProvider } from "@/contexts/UserContext";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const mochiyPopOne = Mochiy_Pop_One({
  variable: "--font-mochiy",
  subsets: ["latin"],
  weight: ["400"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${mochiyPopOne.variable} ${pacifico.variable} antialiased`}
      >
        <NextTopLoader color="#ff6b35" />
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
